HOME_LOSS_ADD = -0.07 # Penalty for home loss
LOSS_CONST = -1 # Value of a standard loss
MAX_POINT_DIFF = 42 # Maximum point differential
MAX_RATING = 0.99 # Maximum rating to avoid 0 values for losing to an undefeated team
MAX_WINPERC = 0.95 # Maximum winning percentage to avoid 0 values for losing to an undefeated team
MIN_RATING = 0.01 # Minimum rating to avoid 0 values for beating a team with 0 wins
MIN_WINPERC = 0.05 # Minimum winning percentage to avoid 0 values for beating a team with 0 wins
NON_FBS_MULT = 0.5 # Factor to multiply Non-FBS winning percentages by
NON_FBS_RATING = 0.005 # Factor to multiply Non-FBS winning percentages by
NON_FBS_WQ = 0 # Non-FBS opponents are considered to have a win quality average of 0
PER_POINT_MULT = 0.01 # Value of each point in point differential
RAW_WQ_MULT = 1.00 # The percentage of the total counted for win quality in first iteration
RAW_SOS_MULT = 0.00 # The percentage of the total counted for strength of schedule in first iteration
ROAD_WIN_ADD = 0.07 # Bonus for road win
SOS_MULT = 0.05 # The percentage of the total counted for strength of schedule in second iteration
WIN_CONST = 1 # Value of a standard win
WQ_MULT = 0.95 # The percentage of the total counted for win quality in second iteration
